# Generated by Django 5.0.6 on 2024-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryMan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='email',
            field=models.EmailField(default='ABC@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='phone',
            field=models.CharField(default='xxxxxxxxxx', max_length=12),
        ),
    ]
